apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "dockercoins.fullname" . }}-redis
  labels:
    app: {{ template "dockercoins.name" . }}-redis
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ template "dockercoins.name" . }}-redis
  template:
    metadata:
      labels:
        app: {{ template "dockercoins.name" . }}-redis
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ template "dockercoins.fullname" . }}-redis
        image: {{ .Values.images.redis.repository }}:{{ .Values.images.redis.tag }}
        imagePullPolicy: {{ .Values.config.imagePullPolicy }}
        ports:
        - name: container
          containerPort: 6379
        env: []