apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "dockercoins.fullname" . }}-worker
  labels:
    app: {{ template "dockercoins.name" . }}-worker
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ template "dockercoins.name" . }}-worker
  template:
    metadata:
      labels:
        app: {{ template "dockercoins.name" . }}-worker
    spec:
      containers:
      - name: {{ template "dockercoins.fullname" . }}-worker
        image: {{ .Values.images.worker.repository }}:{{ .Values.images.worker.tag }}
        imagePullPolicy: {{ .Values.config.imagePullPolicy }}
        ports:
        - name: {{ template "dockercoins.name" . }}-worker
          containerPort: 8001
        env: []